# Generated by Django 3.2.5 on 2021-07-29 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('Rp', 'RiotPoints'), ('Guide', 'Rehber'), ('Karakterler', 'Şampiyonlar')], default='RiotPoints', max_length=20),
        ),
    ]
