# Generated by Django 3.2.5 on 2021-07-29 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_post_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post', verbose_name='Resim'),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('Rp', 'RiotPoints'), ('Guide', 'Rehber'), ('Karakterler', 'Şampiyonlar')], default='RiotPoints', max_length=20, verbose_name='İçerik'),
        ),
    ]
